language: python
sudo: enabled
notifications:
  email:
    recipients:
      - lika27@163.com
    on_success: change # default: change
    on_failure: always # default: always
python:
  - 3.6
before_install:
  - pip install -r requirements.txt
  - sudo apt-get install fonts-droid ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-ukai fonts-arphic-uming
  - sudo fc-cache -f -v
script:
  - python3 send_email.py
